//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRA.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRA.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please speak to the system administrator.
        /// </summary>
        public static string AdminMessage {
            get {
                return ResourceManager.GetString("AdminMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any attendance registry.
        /// </summary>
        public static string AttendanceHistoryEmptyMessage {
            get {
                return ResourceManager.GetString("AttendanceHistoryEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not possible to get your attendance registry.
        /// </summary>
        public static string AttendanceHistoryMessage {
            get {
                return ResourceManager.GetString("AttendanceHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance History.
        /// </summary>
        public static string AttendanceHistoryTitle {
            get {
                return ResourceManager.GetString("AttendanceHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attendance was not registered.
        /// </summary>
        public static string AttendanceNotRegisteredMessage {
            get {
                return ResourceManager.GetString("AttendanceNotRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Attendance was Registered.
        /// </summary>
        public static string AttendanceRegisteredMessage {
            get {
                return ResourceManager.GetString("AttendanceRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Registry.
        /// </summary>
        public static string AttendanceRegistryTitle {
            get {
                return ResourceManager.GetString("AttendanceRegistryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassLabel {
            get {
                return ResourceManager.GetString("ClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string ClassroomLabel {
            get {
                return ResourceManager.GetString("ClassroomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Schedule.
        /// </summary>
        public static string ClassScheduleText {
            get {
                return ResourceManager.GetString("ClassScheduleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any collection assigned.
        /// </summary>
        public static string CollectionEmptyListMessage {
            get {
                return ResourceManager.GetString("CollectionEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any collection in progress.
        /// </summary>
        public static string CollectionInProgressEmptyListMessage {
            get {
                return ResourceManager.GetString("CollectionInProgressEmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not possible to get your collections.
        /// </summary>
        public static string CollectionMessage {
            get {
                return ResourceManager.GetString("CollectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of your collection is.
        /// </summary>
        public static string CollectionStateMessage {
            get {
                return ResourceManager.GetString("CollectionStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection information.
        /// </summary>
        public static string CollectionTableSectionTitle {
            get {
                return ResourceManager.GetString("CollectionTableSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        public static string CollectorUser {
            get {
                return ResourceManager.GetString("CollectorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string CourseNameLabel {
            get {
                return ResourceManager.GetString("CourseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish collection.
        /// </summary>
        public static string FinishButtonText {
            get {
                return ResourceManager.GetString("FinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not possible to finish the collection now.
        /// </summary>
        public static string FinishCollectionErrorMessage {
            get {
                return ResourceManager.GetString("FinishCollectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to finish the collection?.
        /// </summary>
        public static string FinishCollectionMessage {
            get {
                return ResourceManager.GetString("FinishCollectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR Code.
        /// </summary>
        public static string GenerateQRCodeText {
            get {
                return ResourceManager.GetString("GenerateQRCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgressStateCollection {
            get {
                return ResourceManager.GetString("InProgressStateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials inserted are not valid.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your device to a network.
        /// </summary>
        public static string NoConnectivity {
            get {
                return ResourceManager.GetString("NoConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no network connectivity.
        /// </summary>
        public static string NoConnectivityMessage {
            get {
                return ResourceManager.GetString("NoConnectivityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoMessage {
            get {
                return ResourceManager.GetString("NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials don&apos;t allow to use the app.
        /// </summary>
        public static string NoRoleAvailable {
            get {
                return ResourceManager.GetString("NoRoleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesEntryText {
            get {
                return ResourceManager.GetString("NotesEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string NotStartedStateCollection {
            get {
                return ResourceManager.GetString("NotStartedStateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkMessage {
            get {
                return ResourceManager.GetString("OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login.
        /// </summary>
        public static string OperationNotPossibleMessage {
            get {
                return ResourceManager.GetString("OperationNotPossibleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Date.
        /// </summary>
        public static string RegistryDateLabel {
            get {
                return ResourceManager.GetString("RegistryDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to enter as.
        /// </summary>
        public static string RolesPageTitle {
            get {
                return ResourceManager.GetString("RolesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning will happen automatically.
        /// </summary>
        public static string ScanBottomText {
            get {
                return ResourceManager.GetString("ScanBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string ScanButton {
            get {
                return ResourceManager.GetString("ScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold your phone up to the QR Code.
        /// </summary>
        public static string ScanTopText {
            get {
                return ResourceManager.GetString("ScanTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search attendance registrations ....
        /// </summary>
        public static string SearchBarText {
            get {
                return ResourceManager.GetString("SearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string SemesterRepresentLabel {
            get {
                return ResourceManager.GetString("SemesterRepresentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not possible to start the collection now.
        /// </summary>
        public static string StartCollectionErrorMessage {
            get {
                return ResourceManager.GetString("StartCollectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your collection was started.
        /// </summary>
        public static string StartCollectionMessage {
            get {
                return ResourceManager.GetString("StartCollectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your credentials.
        /// </summary>
        public static string StudentNumberFieldEmpty {
            get {
                return ResourceManager.GetString("StudentNumberFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence registration information.
        /// </summary>
        public static string StudentTableSectionTitle {
            get {
                return ResourceManager.GetString("StudentTableSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string StudentUser {
            get {
                return ResourceManager.GetString("StudentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string TeacherNameLabel {
            get {
                return ResourceManager.GetString("TeacherNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, try again.
        /// </summary>
        public static string TryAgainMessage {
            get {
                return ResourceManager.GetString("TryAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesMessage {
            get {
                return ResourceManager.GetString("YesMessage", resourceCulture);
            }
        }
    }
}
